[package]
name = "madxls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[[bin]]
name = "madx_scanner"
path = "bin/scanner.rs"

[[bin]]
name = "madxls"
path = "bin/server.rs"

[dependencies]
atomic_refcell = "*"
tokio = { version = "1.28.2", features = ["io-util", "io-std", "macros", "rt-multi-thread"] }
tower-lsp = "0.20.0"
dashmap = "*"
log = "*"
log4rs = "*"
once_cell = "*"
clap = { version = "*", features = ["derive"] }
anyhow = "*"
